import type { Concert } from "@/types/concert"

export const sampleConcerts: Concert[] = [
  {
    id: "1",
    date: "2025-01-18",
    venue: "Zepp Shinjuku",
    prefecture: "東京都",
    concertName: "夜の終わり TOUR 2025",
    artists: ["yoasobi", "iri"],
  },
  {
    id: "2",
    date: "2025-02-08",
    venue: "大阪城ホール",
    prefecture: "大阪府",
    concertName: "BUMP OF CHICKEN TOUR 2025",
    artists: ["BUMP OF CHICKEN"],
  },
  {
    id: "3",
    date: "2025-02-22",
    venue: "日本武道館",
    prefecture: "東京都",
    concertName: "Mrs. GREEN APPLE CONCERT",
    artists: ["Mrs. GREEN APPLE"],
  },
  {
    id: "4",
    date: "2025-03-15",
    venue: "Zepp Osaka Bayside",
    prefecture: "大阪府",
    concertName: "Awesome City Club LIVE 2025",
    artists: ["Awesome City Club"],
  },
  {
    id: "5",
    date: "2025-03-29",
    venue: "Zepp Shinjuku",
    prefecture: "東京都",
    concertName: "indigo la End TOUR",
    artists: ["indigo la End"],
  },
  {
    id: "6",
    date: "2025-04-12",
    venue: "さいたまスーパーアリーナ",
    prefecture: "埼玉県",
    concertName: "ONE OK ROCK STADIUM LIVE",
    artists: ["ONE OK ROCK"],
  },
  {
    id: "7",
    date: "2025-04-26",
    venue: "マリンメッセ福岡",
    prefecture: "福岡県",
    concertName: "King Gnu TOUR 2025",
    artists: ["King Gnu"],
  },
  {
    id: "8",
    date: "2025-05-03",
    venue: "日本武道館",
    prefecture: "東京都",
    concertName: "ヨルシカ LIVE 2025",
    artists: ["ヨルシカ"],
  },
  {
    id: "9",
    date: "2025-05-17",
    venue: "Zepp Shinjuku",
    prefecture: "東京都",
    concertName: "緑黄色社会 バンドワゴン",
    artists: ["緑黄色社会"],
  },
  {
    id: "10",
    date: "2025-06-07",
    venue: "ロームシアター京都",
    prefecture: "京都府",
    concertName: "Aimer Hall Tour 2025",
    artists: ["Aimer"],
  },
  {
    id: "11",
    date: "2025-06-21",
    venue: "大阪城ホール",
    prefecture: "大阪府",
    concertName: "RADWIMPS LIVE TOUR",
    artists: ["RADWIMPS"],
  },
  {
    id: "12",
    date: "2025-07-05",
    venue: "国立競技場",
    prefecture: "東京都",
    concertName: "米津玄師 STADIUM LIVE",
    artists: ["米津玄師"],
  },
  {
    id: "13",
    date: "2025-07-19",
    venue: "Zepp Nagoya",
    prefecture: "愛知県",
    concertName: "The Oral Cigarettes TOUR",
    artists: ["The Oral Cigarettes"],
  },
  {
    id: "14",
    date: "2025-08-02",
    venue: "日本武道館",
    prefecture: "東京都",
    concertName: "sumika 武道館公演",
    artists: ["sumika"],
  },
  {
    id: "15",
    date: "2025-08-23",
    venue: "幕張メッセ",
    prefecture: "千葉県",
    concertName: "SUMMER SONIC 2025",
    artists: ["yoasobi", "King Gnu", "緑黄色社会", "Aimer"],
  },
  {
    id: "16",
    date: "2025-09-06",
    venue: "Zepp Shinjuku",
    prefecture: "東京都",
    concertName: "YOASOBI ONEMAN LIVE",
    artists: ["yoasobi"],
  },
  {
    id: "17",
    date: "2025-09-20",
    venue: "大阪城ホール",
    prefecture: "大阪府",
    concertName: "BUMP OF CHICKEN AUTUMN",
    artists: ["BUMP OF CHICKEN"],
  },
  {
    id: "18",
    date: "2025-10-11",
    venue: "横浜アリーナ",
    prefecture: "神奈川県",
    concertName: "King Gnu Hall Tour",
    artists: ["King Gnu"],
  },
  {
    id: "19",
    date: "2025-11-01",
    venue: "日本武道館",
    prefecture: "東京都",
    concertName: "ヨルシカ武道館2025",
    artists: ["ヨルシカ"],
  },
  {
    id: "20",
    date: "2025-11-22",
    venue: "さいたまスーパーアリーナ",
    prefecture: "埼玉県",
    concertName: "Mrs. GREEN APPLE ARENA",
    artists: ["Mrs. GREEN APPLE"],
  },
]
